server:
  port: 9090
spring:
  main:
    allow-circular-references: true
  application:
    name: service-gateway
  config:
    import: optional:configserver:http://ms-config-server:8888
  cloud:
    gateway:
      default-filters:
        - name: SCGWGlobalFilter